---
- name: copy nginx configuration
  sudo: yes
  copy:
    src: marathon.nginx
    dest: /etc/nginx/templates
  notify:
    - reload nginx
  tags:
    - marathon

- name: write nginx config vars
  run_once: yes
  command: consul-cli kv-write --token={{consul_acl_secure_token}} secure/marathon/nginx/do_ssl {{do_marathon_ssl}}
  tags:
    - marathon

- name: write nginx config vars
  run_once: yes
  command: consul-cli kv-write --token={{consul_acl_secure_token}} secure/marathon/nginx/do_auth {{do_marathon_auth}}
  tags:
    - marathon

- name: write nginx config vars
  run_once: yes
  command: consul-cli kv-write --token={{consul_acl_secure_token}} secure/marathon/proxy_port {{ marathon_proxy_port }}
  tags:
    - marathon

- name: write nginx config vars
  run_once: yes
  command: consul-cli kv-write --token={{consul_acl_secure_token}} secure/marathon/port {{ marathon_port }}
  tags:
    - marathon
