mantlui_nginx_image: ciscocloud/nginx-mantlui
mantlui_nginx_image_tag: 0.7.1
do_mantlui_ssl: false
do_mantlui_auth: false

mantlui_nginx_cert: /etc/pki/mantl/cert
mantlui_nginx_key: /etc/pki/mantl/key
